//https://medium.com/@simondlr/tokens-2-0-curved-token-bonding-in-curation-markets-1764a2e0bee5
//https://medium.com/@simondlr/what-is-harberger-tax-where-does-the-blockchain-fit-in-1329046922c6
//https://blog.usejournal.com/crypto-commons-da602fb98138


function drawNotes() {
    var text = {
	opacityNotes: "Opacity means that we don't know the exact nature of the relationship.",
	syrianCrisisNotes: "Here's a relevant section from <a href='https://journals.ametsoc.org/doi/full/10.1175/WCAS-D-13-00059.1' target='_blank'>a recent paper</a> of Peter Gleick's. Peter is a world-renowned expert on water issues and climate change.<p class='highlight-quotation'>Between 2006 and 2009, around 1.3 million inhabitants of eastern Syria were affected by agricultural failures. An estimated 800 000 people lost their livelihoods and basic food supports (Solh 2010). During this period, yields of wheat and barley dropped 47% and 67%, respectively, and livestock populations plummeted (ACSAD 2011). A return of drought in 2011 worsened the situation. By late 2011, the UN estimated that between two million and three million people were affected, with a million driven into food insecurity. More than 1.5 million people—mostly agricultural workers and family farmers—moved from rural land to cities and camps on the outskirts of Syria’s major cities of Aleppo, Damascus, Dara’a, Deir ez-Zour, Hama, and Homs.</p><p class='notes-final-p'>The whole paper is worth checking out.</p>",
	chaosNotes: "In his book Chaos: Making a New Science, the science historian James Gleick notes that none of the chaos scientists he interviewed 'could quite agree on [a definition of] the word itself'.",
	    seaLevelNotes: "In a <a href='https://www.sciencedirect.com/science/article/pii/S0012821X14007961' target='_blank'>2015 study</a>, Pollard and colleagues showed that when two (often ignored) mechanisms are added to an ice sheet model — hydrofracturing by surface water, and large ice cliff failure — the model produced a 17m sea-level rise over thousands of years and 5m over a couple of hundred (when simulated with a similar climate to past warm periods).<p>This compares to the rather conservative <a href='http://www.realclimate.org/index.php/archives/2013/10/sea-level-in-the-5th-ipcc-report/' target='_blank'>IPCC estimates</a> of 52-98 cm by the year 2100 (under high emissions scenarios), and 28-61 cm under aggressive emissions reductions.</p><p>In <a href='http://iopscience.iop.org/article/10.1088/1748-9326/9/10/104008/pdf' target='_blank'>another study</a> addressing sea level projections for 2100, Jevrejeva and colleagues come up with an upper limit of 180cm. However, they are transparent with respect to the uncertainties involved:</p><p>'large uncertainties remain due to the lack of scenario-dependent projections from ice sheet dynamical models, particularly for mass loss from marine-based fast flowing outlet glaciers in Antarctica. This leads to an <span class='bold'>intrinsically hard to quantify fat tail in the probability distribution for global mean sea level rise. Thus our low probability upper limit of sea level projections cannot be considered definitive.'</span></p>",
	    gulfStreamNotes: "In short, a higher global temperature leads to more ice melting which leads to more freshwater in the oceans which slows down the Gulf stream. At some stage a small increase in temperature will cause us to cross a tipping point — in other words, at some unknown point, a small change in freshwater levels could have a large irreversible effect (the Gulf stream could collapse). This would affect the distribution of heat between Europe and America in a big way — some European countries could experience winters that are on average -5 to -10°C colder, in contrast some areas of the United States could be 2 to 4°C warmer.<p>Early last year, Stefan Rahmstorf wrote <a target='_blank' href='http://www.realclimate.org/index.php/archives/2017/01/the-underestimated-danger-of-a-breakdown-of-the-gulf-stream-system/'>a piece</a> focused on a <a href='http://advances.sciencemag.org/content/3/1/e1601666' target='_blank'>recent study</a> in Science Advances by Wei Liu and his colleagues concerning the overlooked possibility of the Gulf Stream collapsing. The two key takeaways are:</p><p>1) There’s an unquantifiable risk of abrupt (non-linear) climate changes.</p><p>2) Our best mathematical models are biased and inaccurate.</p><p><a href='https://www.theatlantic.com/science/archive/2017/01/what-a-real-debate-looks-like-in-climate-science/512444/' target='_blank'>Further reading</a></p>",
	    uncertaintyNotes:"An extract from a <a href='http://www.rff.org/research/publications/confidence-trap-balancing-proof-burden-climate-conversation' target='_blank'>recent interview with Roger Cooke</a>, a lead author of the chapter on risk and uncertainty in the Intergovernmental Panel on Climate Change's Fifth Assessment Report:<p>[the IPCC] tends to downplay scientific disagreement where consensus is weaker. Second, it invites us to fall into the confidence trap in thinking that high confidence in each [event] is the same as high confidence in all [events].</p><p>We can find an example of downplaying disagreements in the IPCC's Fifth Assessment Report, where it covers equilibrium climate sensitivity (ECS), the amount of warming eventually attained by a doubling of carbon dioxide in the atmosphere (see box 12.2): <a href='https://www.ipcc.ch/pdf/assessment-report/ar5/wg1/WG1AR5_Chapter12_FINAL.pdf' target='_blank'>'ECS is positive, extremely unlikely less than 1°C (high confidence), and very unlikely greater than 6°C (medium confidence).'</a></p><p>The attention is directed to the (rather wide) interval in which the scientific consensus bounds equilibrium climate sensitivity. On one hand, a value of less than 1°C is good news for business as usual. On the other, highly regarded climate scientist David Archer says “a climate change of … 5–6°C, would be catastrophic to human civilization” (The Long Thaw, Princeton University Press; p. 95).</p>",
	    pseudoProbNotes: "Here’s an extract from a <a href='http://www.rff.org/research/publications/confidence-trap-balancing-proof-burden-climate-conversation' target='_blank'>recent interview with Roger Cooke</a> that talks more about this:<p class='highlight-quotation'>Every time I read that the IPCC or some other climate committee used their own expert judgment, I recall <a href='https://academic.oup.com/reep/article/12/1/113/4835830'target='_blank'>our review of recent studies on structured expert judgment.</a> Experts quantified their uncertainty about things from their field that are known post hoc.</p><p class='highlight-quotation'>The hypothesis that an expert is statistically accurate would be rejected at the 5 percent level for nearly three quarters of the 320 experts in the studies we reviewed. About half would be rejected at the 0.5 percent level.</p><p class='notes-final-p'>In plain english: there's science to suggest that probabilistic statements based on expert judgement are flawed.</p>",
	    naturalMethodsNotes: "James Hansen and colleagues suggest that natural methods have the potential to extract <a href='' target='_blank'>100 Gigatons of carbon by the end of this century</a> (see section 9.1) — <a href='https://thinkprogress.org/the-biggest-source-of-mistakes-c-vs-co2-c0b077313b' target='_blank'>that's about 365 GT of carbon dioxide.</a><p>The IPCC has been more conservative. It has estimated that <a href='https://www.theguardian.com/environment/2012/nov/29/planting-trees-climate-change' target='_blank'>tree-planting</a> can remove between <a href='http://www.ipcc.ch/ipccreports/sres/land_use/151.htmB' target='_blank'>1.1–1.6 GT of carbon dioxide per year</a> — that's 88-126 GT over 80 years.</p><p>To put these numbers in context, we're emitting around 40 gigatons of carbon dioxide a year at the moment.</p>",
	extractionNotes: "This information is taken from a <a href='https://www.earth-syst-dynam.net/8/577/2017/esd-8-577-2017.pdf' target='_blank'>recent paper by Hansen and colleagues (see section 7).</a> The total amount of carbon dioxide that needs to be removed depends on the fossil fuels emissions scenario as well as the Earth's carbon cycle — which includes ocean uptake of carbon, deforestation, forest regrowth and carbon storage in the soil — Hansen and colleagues chose to model the carbon cycle using a version of the simple and well-tested Bern carbon cycle model (see section 7 of the paper for more about this choice).<p>Note that the amount of carbon dioxide we have to extract from the atmosphere is greater than the difference between the atmospheric amount without extraction and the target amount. For example, if emissions stay constant and we don't extract any, then by the end of this century the concentration of carbon dioxide will be around 547 ppm.</br> 547 - 350 = 197 ppm. But to achieve a target of 350 ppm, we'll need to extract 328ppm.</p><p class='notes-final-p'>That’s because, <a href='http://iopscience.iop.org/article/10.1088/1748-9326/11/9/095012/pdf' target='_blank'>as the amount of CO<sub>2</sub> in the atmosphere decreases the earth becomes less effective at absorbing it</a>: the oceans absorb less CO<sub>2</sub>, vegetation converts CO<sub>2</sub> into biomass at a slower rate, and <a href='http://iopscience.iop.org/article/10.1088/1748-9326/5/2/024011/meta' target='_blank'>more carbon dioxide is released from the Earth’s interior at midocean ridges and hotspot volcanoes</a> (what scientists refer to as ocean outgassing).</p>",
	hansenCalculationNotes: "Simulating future atmospheric CO<sub>2</sub> as a function of a fossil fuel emission scenario requires modelling the Earth’s carbon cycle, including ocean uptake of carbon, deforestation, forest regrowth and carbon storage in the soil. Hansen and colleagues chose to model the carbon cycle using a version of the simple and well-tested Bern carbon cycle model (<a href='https://www.earth-syst-dynam.net/8/577/2017/esd-8-577-2017.pdf' target='_blank'>see section 7 of this paper</a> for more about this choice).",
	    treeNotes: "According to the College of Agriculture & Life Sciences at NC State University <a href='https://projects.ncsu.edu/project/treesofstrength/treefact.htm' target='_blank'>a tree ‘can sequester 1 ton of carbon dioxide by the time it reaches 40 years old.'</a><p>We've just mentioned that Lackner’s artificial trees can sequester 1 ton of carbon dioxide a day, which comes to 365 tons a year.</p><p>Over 40 years that's 365 * 40 = 14,600 tons.</p><p>So, even with a large margin of error, Lackner’s artificial trees are easily 10,000 times more effective than nature’s equivalent.</p>",
	    futurePredictionNotes: "The British science writer and futurist, Sir Arthur Charles Clarke (also known for co-writing the screenplay of 2001: A Space Odyssey) wrote a <a href='https://stacks.stanford.edu/file/druid:mt534kj6459/mt534kj6459.pdf' target='_blank'>couple of essays</a> in which he explored this subject in great depth.<p>From Arthur C. Clarke's <a href='https://stacks.stanford.edu/file/druid:mt534kj6459/mt534kj6459.pdf' target='_blank'>'Hazards of Prophecy: Failure of Nerve':</a></p><p>With monotonous regularity, apparently competent men have laid down the law about what is technically possible or impossible — and have been proved utterly wrong, sometimes while the ink was scarcely dry from their pens. On careful analysis, it appears that these debacles fall into two classes, which I will call 'failures of nerve' and 'failures of imagination'.</p><p>The failure of nerve seems to be the more common; it occurs when even given all the relevant facts the would-be prophet cannot see that they point to an inescapable conclusion. Some of these failures are so ludicrous as to be almost unbelievable, and would form an interesting subject for psychological analysis. 'They said it couldn't be done' is a phrase that occurs throughout the history of invention; I do not know if anyone has ever looked into the reasons why 'they' said so, often with quite unnecessary vehemence.</p>",
	    scientistPredictionNotes: "From Arthur C. Clarke's <a href='https://stacks.stanford.edu/file/druid:mt534kj6459/mt534kj6459.pdf' target='_blank'>'Hazards of Prophecy: Failure of Imagination':</a><p>Another celebrated failure of imagination was that persisted in by Lord Rutherford, who more than any other man laid bare the internal structure of the atom. <span class='bold'>Rutherford frequently made fun of those sensation mongers who predicted that we would one day be able to harness the energy locked up in matter.</span> Yet only five years after his death in 1937, die first chain reaction was started in Chicago. <span class='bold'>What Rutherford, for all his wonderful insight, had failed to take into account was that a nuclear reaction might be discovered that would release more energy than that required to start it.</span> To liberate the energy of matter, what was wanted was a nuclear 'fire' analogous to chemical combustion, and the fission of uranium provided this. <span class='bold'>Once that was discovered, the harnessing of atomic energy was inevitable, though without the pressures of war it might well have taken the better part of a century.</span></p><p><span class='bold'>The example of Lord Rutherford demonstrates that it is not the man who knows most about a subject, and is the acknowledged master of his field, who can give the most reliable pointers to its future.</span> Too great a burden of knowledge can clog the wheels of imagination.</p>",
	    solarCellNotes:"This figure comes from <a href='https://books.google.co.uk/books?id=L55ODwAAQBAJ&pg=PA34&dq=a+1-watt+solar+cell+cost+$286+to+produce&hl=en&sa=X&ved=0ahUKEwjKhMDi2IfbAhUMPsAKHX0AAakQ6AEIKTAA#v=onepage&q=a%201-watt%20solar%20cell%20cost%20%24286%20to%20produce&f=false' target='_blank'>Varun Sivaram's book 'Taming the Sun: Innovations to Harness Solar Energy and Power the Planet'.</a> Assuming the $286 figure is correct, we can double check the figure for the estimated cost by dividing $1,400,000 by $286 to get the total number of watts that were assumed to be required to power an American home.<p>Total number of watts = 1,400,000 / 286 ≈ 5000</p><p>That sounds about right. If anything it's a conservative estimate: <a href='https://en.wikipedia.org/wiki/Rooftop_photovoltaic_power_station' target='_blank'>wikipedia tells us that rooftop solar systems on residential buildings typically feature a capacity of about 5000 to 20,000 watts.</a></p>",
	    solarProductionNotes:"The 20% figure comes from the 'Key findings' section of a <a href='https://www.irena.org/documentdownloads/publications/re_technologies_cost_analysis-solar_pv.pdf' target='_blank'>2012 report by The International Renewable Energy Agency (IRENA).</a> The direct quotation is:  'PV module costs have a learning rate of 22%, implying that costs will decline by just over a fifth with every doubling of capacity. Continued rapid cost reductions are likely due to the rapid growth in deployment, given that cumulative installed capacity grew by 71% in 2011 alone.'<p>The 7% figure comes from a <a href='http://rameznaam.com/2011/03/17/the-exponential-gains-in-solar-power-per-dollar/' target='_blank'>very interesting 2011 article</a> by one of the few exponential thinkers in this space, Ramez Naam. Here's the relevant extract from it:</p><p>'Averaged over 30 years, the trend is for an annual 7 percent reduction in the dollars per watt of solar photovoltaic cells…</p><p>What’s driving these changes?  There are two factors.  First, solar cell manufacturers are learning – much as computer chip manufacturers keep learning – how to reduce the cost to fabricate solar.</p><p>Second, the efficiency of solar cells – the fraction of the sun’s energy that strikes them that they capture – is continually improving.</p>",
	    lacknerCostEstimateNotes:"In a <a href='http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.468.9580&rep=rep1&type=pdf' target='_blank'>2009 paper, titled 'Capture of carbon dioxide from ambient air'</a>, Lackner notes that:<p>The operational costs will come down, as maintenance costs are reduced and one-of-a-kind pieces of equipment enter into mass production. At 5¢ /kWh the cost of 50 kJ/mol CO2 of electricity amounts to $16 per ton of CO2. Some further reduction in energy consumption certainly appears feasible, and thus it seems quite plausible that the long term price of air capture could drop as low as $30/ton of CO2.</p>",
	    lacknerHardProblemsNotes: "The biggest one is probably storage; Lowering the carbon dioxide concentration by 100 ppm would require a storage space almost as large as Lake Michigan. Luckily, there are various <a href='http://www.bgs.ac.uk/discoveringGeology/climateChange/CCS/howCanCo2BeStored.html' target='_blank'>interesting options worth pursuing</a><p>For example, large rock (peridotite) deposits in Oman could be used to chemically bind carbon dioxide as magnesium carbonate. <a href='https://www.nytimes.com/interactive/2018/04/26/climate/oman-rocks.html?action=click&module=MoreInSection&pgtype=Article&region=Footer&contentCollection=Climate%20and%20Environment' target='_blank'>In theory, these rocks could store hundreds of years of human emissions of carbon dioxide.</a> (Whether the citizens of Oman are happy for their land to be a part of such a plan, is an ethical question that would of course need to be addressed). Further, while the formations in Oman are special, they are not unique. Smaller ones are found in Northern California, Papua New Guinea and Albania, among other places.</p><p>For more on Oman’s potential to store carbon dioxide (and the challenges involved) see this excellent <a href='https://www.nytimes.com/interactive/2018/04/26/climate/oman-rocks.html?action=click&module=MoreInSection&pgtype=Article&region=Footer&contentCollection=Climate%20and%20Environment' target='_blank'>New York Times piece.</a></p><p>Another potential option is to <a href='http://www.pnas.org/content/103/33/12291.short' target='_blank'>inject the captured carbon dioxide into deep-sea sediments</a> (less than 3,000-m water depth and a few hundred meters of sediment) . The total storage capacity within the 200-mile economic zone of the U.S. coastline alone is capable of storing thousands of years of current U.S. CO2 emissions.</p>",
	    lacknersHistoryNotes:"Lackner was the first person to really think about this. Here’s an extract from an excellent article about the current state of the technology and his journey so far:<p>'As the world's population skyrocketed in the early 1990s, Lackner thought only of how much energy those people would soon consume. He wasn’t tempted by the cold-fusion experiments that thrilled the scientific world, promising unlimited free energy. In the meantime, the world would continue burning massive amounts of fossil fuels and ignoring the waste. Atmospheric CO2 levels would climb ever higher. The system would soon collapse.</p><p>It was a waste-management problem, he realized. The bathtub was already full, and people kept trying to add more water. Somebody had to release the drain.</p><p>“We need to clean up after ourselves,” he said. “By now, we don’t have a choice anymore.”'</p><p>Relevant papers:</p><p><a href='https://pdfs.semanticscholar.org/1976/4d0ef804f5447268659045527b7f99769395.pdf' target='_blank'>Carbon Dioxide Extraction From Air: Is It An Option? (1999)</a></p><p><a href='http://www.pnas.org/content/109/33/13156' target='_blank'>The urgency of the development of CO2 capture from ambient air (2011)</a></p>",
	    biocharNotes:"Biochar basically involves transforming the carbon in biomass into stable carbon structures. These structures can remain in soils for thousands of years",
	    gulfStreamSecondNotes:"<p>For those unfamiliar, the AMOC is responsible for circulating heat from the tropics and Southern Hemisphere toward the North Atlantic, where the heat is then transferred to the atmosphere. It's an essential part of the Earth's climate system.</p><p>Most abrupt climate changes are likely due to sudden circulation shifts. And the best-known examples are the several dozen shutdowns of the AMOC during the last ice age.</p><p>Here's what Stefan Rahmstorf — renowned climate scientist and co-author of the study — had to say about the current slowdown:</p><p><span class='highlight-quotation'>We know somewhere out there is a tipping point where this current system is likely to break down...We still don't know how far away or close to this tipping point we might be... This is uncharted territory.</span></p>",
	    butterflyEffectNotes:"",
	    ipccRecentReportNotes:"See table 12.4 of <a href='https://www.ipcc.ch/pdf/assessment-report/ar5/wg1/drafts/fgd/WGIAR5_WGI-12Doc2b_FinalDraft_Chapter12.pdf' target='_blank'>this document.</a><p>Note that <a href='http://www.ipcc.ch/pdf/supporting-material/uncertainty-guidance-note.pdf'>according to the IPCC's uncertainty guidance, confidence is expressed qualititatively and is at least partly dependent on expert judgement.</a></p>",
	    ipccConfidenceNotes:"It's worth remarking that the IPCC wasn't always so confident about it's ability to express the risk of abrupt climate changes. Back in 2001 it was much more explicit about the difficulties involved with attaching probabilities to these rapid and unexpected events:<p><span class='highlight-quotation'>A non-linear system such as the climate system may exhibit rapid climate change as a response to internal processes or rapidly changing external forcing. Because the probability of their occurrence may be small and their predictability limited, they are colloquially referred to as unexpected events or surprises.</span> 🎉</p><p>Finally, here's a <a href='http://www.fooledbyrandomness.com/climateletter.pdf' target='_blank'>relevant letter</a> written by a group of complex scientists that highlights the need for precaution given the inherent uncertainties surrounding complex systems.</p>The conclusion:<p class='highlight-quotation'>Push a complex system too far and it will not come back. The popular belief that uncertainty undermines the case for taking seriously the 'climate crisis' that scientists tell us we face is the opposite of the truth. Properly understood, as driving the case for precaution, uncertainty radically underscores that case, and may even constitute it.</p>",
	    abruptClimateChangesNotes:"According to the Committee on Abrupt Climate Change of the National Research Council, there are two definitions of abrupt climate change:<p>1) In terms of physics, it is a 'transition of the climate system into a different mode on a time scale that is faster than the responsible forcing' (a forcing is any factor that affects the earth’s energy-balance — and hence climate)</p><p>2) In terms of impacts, <span class='bold'>'an abrupt change is one that takes place so rapidly and unexpectedly that human or natural systems have difficulty adapting to it.'</span></p><p>These definitions are complementary. The first gives us some insight into how abrupt climate change comes about. And the second explains why we should care.</p><p>Finally, here are a couple of relevant extracts from <a href='https://en.wikipedia.org/wiki/Abrupt_climate_change' target='_blank'>the abrupt climate change wikipedia page:</a></p><p class='highlight-quotation'>Scientific understanding of abrupt climate change is generally poor.</p><p class='highlight-quotation notes-final-p'>Factors that may increase the probability of abrupt climate change include higher magnitudes of global warming, warming that occurs more rapidly, and warming that is sustained over longer time periods.</p>",
	    expertJudgementIPCCNotes:"Here's a relevant extract from a recent <a href='http://www.rff.org/research/publications/confidence-trap-balancing-proof-burden-climate-conversation' target='_blank'> interview with the lead author of the chapter on risk and uncertainty in the IPCC's Fifth Assessment Report,  Roger Cooke:</a><p class='highlight-quotation'>Broadly speaking, the IPCC has done a monumental job of cataloging the current state of the science on climate change and defining where scientific consensus lies... [but] it tends to downplay scientific disagreement where consensus is weaker.</p><p class='highlight-quotation'>We can find an example of downplaying disagreements in the IPCC’s Fifth Assessment Report, where it covers equilibrium climate sensitivity (ECS), the amount of warming eventually attained by a doubling of carbon dioxide in the atmosphere <a href='https://www.ipcc.ch/pdf/assessment-report/ar5/wg1/WG1AR5_Chapter12_FINAL.pdf' target='_blank'>(Chapter 12; see Box 12.2): 'ECS is positive, extremely unlikely less than 1°C (high confidence), and very unlikely greater than 6°C (medium confidence).'</a> The attention is directed to the (rather wide) interval in which the scientific consensus bounds equilibrium climate sensitivity. On one hand, a value of less than 1°C is good news for business as usual. On the other, highly regarded climate scientist David Archer says ‘a climate change of … 5–6°C, would be catastrophic to human civilization’ (The Long Thaw, Princeton University Press; p. 95).</p><p class='highlight-quotation notes-final-p'>That eventuality has a likelihood of less than 10 percent (in the IPCC’s calibrated language), which is affirmed with only medium confidence. That’s rather short shrift for a catastrophe to civilization. Would you put your children on an airplane in which authorities had medium confidence that the likelihood of a crash was less than 10 percent?</p>",
	    tetlockNotes: "<a href='https://www.ft.com/content/803a430a-442b-11e6-b22f-79eb4891c97d' target='_blank'>Lunch with the FT: Philip Tetlock</a>",
	    naturalClimateSolutionsNotes: "Cost effective here means not more expensive than $100 per ton of carbon dioxide (note that this value is in line with the social cost of carbon in 2030 estimated to be between $82–$260  to meet the 1.5–2 °C [Paris] climate target).<p>Here’s the logic behind the 550 GT figure:</p><p>The paper outlines a plan that has cost effective natural methods sequestering around 10 GT of carbon dioxide a year for 35 years. They envisage a 10 year linear ramp up to that figure (from 0 to 10). And a 30 year linear ramp down from 10 GT a year back to 0 (as the effectiveness of the natural climate solutions start to naturally taper off).</br>So that’s (10 * 35) + (10 * 5.5) + (30 * 5.5) = 550.</p><p>Note that in the paper, the authors also convert the weight of other greenhouse gases (that natural methods can help sequester) into the carbon dioxide equivalent to come up with a maximum potential of around 11 GT a year instead of 10. I’ve chosen to focus this essay on carbon dioxide, so I’m working with 10 to be consistent.</p>",
	    humanCivilizationNotes:"Note that there's nothing particularly special about 350. It's just a number that's low enough to change the conversation.<p>Once we've reduced carbon dioxide levels to 350ppm, we can re-evaluate effects on ice sheets and other variables (and if necessary move down to 325, or even 300ppm). The important thing is that we're within striking distance of the range of natural temperatures experienced by our ancestors.</p>",
	    risksOnePlanetNotes: "",
	    dayAfterTomorrowNotes: "Back in 2004, Stefan Rahmstorf of the Potsdam Institute for Climate Impact Research, an expert on thermohaline circulation and its effect on climate, said after a talk with scriptwriter Jeffrey Nachmanoff at the film's Berlin preview:<p class='highlight-quotation'>Clearly this is a disaster movie and not a scientific documentary, [and] the film makers have taken a lot of artistic license. But the film presents an opportunity to explain that some of the basic background is right: humans are indeed increasingly changing the climate and this is quite a dangerous experiment, including some risk of abrupt and unforeseen changes ...</p><p class='highlight-quotation notes-final-p'>Luckily it is extremely unlikely that we will see major ocean circulation changes in the next couple of decades (I’d be just as surprised as Jack Hall if they did occur); at least most scientists think this will only become a more serious risk towards the end of the century <a href='https://www.nature.com/articles/s41586-018-0006-5.epdf?referrer_access_token=NL56_45qV256CuItVqPIztRgN0jAjWel9jnR3ZoTv0OdzeJ18XkImxSDnyYEEsE8kZxiCFQRHXUDVk7z88DZuCVSpNT526jCYc7AolNWO0q1VuAzrHmqVEhSpPio75PuDkbmnZMCM7UNkijPz7lF85lllre35b36xIR2bFKP-N' target='_blank'>[note that we've just recently detected a 15% circulation slowdown in the AMOC, which most scientists regard as a major change]</a> And the consequences would certainly not be as dramatic as the 'superstorm' depicted in the movie. Nevertheless, a major change in ocean circulation is a risk with serious and partly unpredictable consequences, which we should avoid. And even without events like ocean circulation changes, climate change is serious enough to demand decisive action.</p>",
	    abruptSeaIceLossNotes:"Present-day observations of Greenland and Antarctica show increasing surface melt, loss of ice shelves, accelerating ice streams, and increasing overall mass loss. These rapid changes do not occur in existing ice sheet models, which are missing critical physics of ice sheet disintegration. Sea level change of several meters per century occur in the paleoclimate record, in response to energy changes slower and weaker than the present human-made changes. It seems likely that large ice sheet response will occur within centuries, if human-made forcings continue to increase. Once ice sheet disintegration is underway, decadal changes of sea level may be substantial.",
	    amocNotes:"For those unfamiliar, the AMOC is an ocean current responsible for circulating heat from the tropics and Southern Hemisphere toward the North Atlantic, where the heat is then transferred to the atmosphere.",
	    unknownUnknownsNotes:"According to the United State's <a href='https://science2017.globalchange.gov/chapter/15/' target='_blank'>Climate Science Special Report</a>:<p class='notes-final-p'>The systematic paleoclimatic model-data mismatch for past warm climates suggests that climate models are omitting at least one, and probably more, processes crucial to future warming, especially in polar regions. For this reason, future changes outside the range projected by climate models cannot be ruled out, and climate models are more likely to underestimate than to overestimate the amount of long-term future change.</p>",
	    ppmNotes:"An atmospheric carbon dioxide level of 350ppm means that if we were to take a random sample of a million air molecules from our atmosphere, we'd expect 350 of them to be carbon dioxide molecules.<p class='notes-final-p'>If you're surprised by how little that is, it's a highly counter-intuitive fact that a small increase to an already small concentration of carbon dioxide in our atmosphere can have large effects on our planet's temperature and environment.</p>",
	    co2tempNotes: "This relation depends on the long term sensitivity of our planet's temperature to carbon dioxide levels — which we can't know for certain. However, our best estimates for this sensitivity are consistent with past climate data (including the amount of warming we've experienced since the industrial revolution. <p class='notes-final-p'>If we assume this relationship holds into the future, it's likely that 350ppm would keep global warming close to 1°C above pre-industrial revolution levels (the current average temperature of our planet.</p>",
	    omanStorageNotes: "One of the harder ones involves figuring out where to store all this carbon dioxide.<p><span class='highlight-quotation'>[Storage] still feels like the most nascent piece of the conversation… You see these sparks, but I don’t see anything catching fire yet.</span></br>— Noah Deich, executive director of the Center for Carbon Removal, a research organization in Berkeley, California</p><p>However, we do have options; one of the most promising involves a rock called peridotite that reacts with CO2 to form solid carbonate. In theory, peridotite rocks in Oman alone could store hundreds of years worth of CO2 emissions.</p><p>According to Peter B. Kelemen, a geologist at Columbia University’s Lamont-Doherty Earth Observatory who has been studying the rocks in Oman for more than two decades, 'The rocks here [in Oman] may be capable of capturing a lot of carbon dioxide, but the challenge is doing it much faster than nature, in huge amounts and at low enough cost to make it more than a pipe dream.'</p><p>For more see this excellent <a href='https://www.nytimes.com/interactive/2018/04/26/climate/oman-rocks.html' target='_blank'>ny times piece.</a></p><p>(Note that while the formations in Oman are special, they are not unique. Similar though smaller ones are found in Northern California, Papua New Guinea and Albania, among other places.)</p>",
	    permafrostNotes: "Permafrost is a (theoretically) permanently frozen layer below the Earths surface. It consists of soil, gravel, and sand, usually bound together by ice.",
	    greenSaharaNotes: "To quote the science journalist Fred Pearce: <p class='highlight-quotation'>The world's largest desert was not always so arid. Where seas of sand now shimmer, there were once vast lakes, swamps and rivers. Lake Chad, which today covers a paltry few hundred square kilometres, was then a vast inland sea, dubbed by scientists Lake Megachad. It was the size of France, Spain, Germany and the UK put together. Today the lake evaporates in the desert sun, but then it overflowed its inland basin and, at different times, drained south via Nigeria into the Atlantic or east down a vast wadi to the Nile...</p><p class='highlight-quotation'>But the African Humid Period came to an end - known as the Fall - suddenly. In the space of a century, the Saharan rivers emptied, swamps dried up and the monsoon rain clouds were replaced by clouds of wind-blown sand.</p><p class='notes-final-p'>For more, see <a href='https://www.sciencedirect.com/science/article/pii/S0012821X14007961' target='_blank'>here.</a></p>",
	methaneHydratesNotes: "A methane hydrate is a solid compound in which a large amount of methane is trapped within a crystal structure of water, forming a solid similar to ice.",
	methane12xNotes: "See the bottom of <a href='https://www.cosis.net/abstracts/EGU2008/01526/EGU2008-A-01526.pdf'>this abstract</a> from a 2008 paper by N. Shakhova,  I. Semiletov, A. Salyuk, and , D. Kosmach.",
	paleoclimateNotes: "Paleoclimatology is the study of changes in climate taken on the scale of the entire history of Earth.",
	paleoclimateNotes2: "Paleoclimatology is the study of changes in climate taken on the scale of the entire history of Earth.",
	removalNotes3: "We'll explore this in a lot of depth in part 2 of this lecture series.",
	cmipNotes: "CMIP5/6 is an international climate model comparison project designed to improve models and our understanding of the climate.",
	}
    var notesCounter = 0;
    var clickOrHover = window.innerWidth >= 900 ? "mouseover" : "click";
    
    d3.selectAll(".highlight").on(clickOrHover,function(d) {
	d3.selectAll('.further-notes').remove();
	d3.event.stopPropagation();
	console.log(this)
	showNotes(this,text[this.id],d3.event.clientY)
	console.log(d3.event.clientY);
	notesCounter = 1;
	console.log(notesCounter);
	
	d3.selectAll('.further-notes').on("click",function(d) {
	    d3.event.stopPropagation();
	    if (window.innerWidth < 900) {
		this.remove();
	    }
	})
    })

    function showNotes(that,text,y) {
	var notes = document.createElement('div');
	notes.className = "further-notes";
	notes.innerHTML = text;
	console.log(that.id);

	var notesTapToClose = document.createElement('div');
	notesTapToClose.className = "notes-tap-to-close";
	notesTapToClose.innerHTML = "— tap to close —"

//	notes.appendChild(notesTapToClose);

	//add to body instead?
	var el = document.getElementById(that.id)
	el.appendChild(notes);
//	var viewportOffset = el.getBoundingClientRect();
	// these are relative to the viewport, i.e. the window
//	var top = viewportOffset.top;
//	var left = viewportOffset.left;
//	var body = d3.select('body');
//	body.node().appendChild(notes);
//	document.getElementById("tooltip-test").appendChild(notes);
	
	
    }
    d3.select('body').on('click', function(d) {
	if (notesCounter === 1)  {
	    d3.selectAll('.further-notes').remove()
	    notesCounter = 0;
	}
    })
}
